#! /usr/bin/env python
# -*- coding: utf-8 -*-

# gracie
# Part of Gracie, an OpenID provider
#
# Copyright © 2007 Ben Finney <ben+python@benfinney.id.au>
# This is free software; you may copy, modify and/or distribute this work
# under the terms of the GNU General Public License, version 2 or later.
# No warranty expressed or implied. See the file LICENSE for details.

""" Application behaviour for Gracie
"""

import optparse
import logging

from server import __version__
from server import GracieServer
from httpserver import default_host, default_port


class OptionParser(optparse.OptionParser):
    """ Commandline option parser for this application """

    def __init__(self):
        """ Set up a new instance """
        optparse.OptionParser.__init__(self)

        self.version = __version__
        self.init_options()

    def init_options(self):
        """ Set up options """

        self.add_option('-V', '--version',
            action='version',
            help="Report version of program and exit",
        )
        self.add_option('--log-level',
            action='store', type='string', default="WARN",
            dest='loglevel', metavar='LEVEL',
            help="Set logging verbosity level to LEVEL",
        )


class Gracie(object):
    """ Behaviour for Gracie application """

    def __init__(self, argv):
        """ Set up a new instance """
        self._process_commandline(argv)
        self._init_logging()
        socket_params = self._get_socket_params()
        self.server = GracieServer(socket_params)

    def _process_commandline(self, argv):
        """ Process command line to this application """
        option_parser = OptionParser()
        (self.opts, self.args) = option_parser.parse_args(argv)

    def _init_logging(self):
        """ Initialise the logging system """
        level = getattr(logging, self.opts.loglevel, None)
        format =  "%(asctime)s %(name)s: %(levelname)s: %(message)s"
        time_format = "%F %T"
        logging.basicConfig(
            level = level,
            format = format, datefmt = time_format,
        )

    def _get_socket_params(self):
        """ Determine the server socket parameters """
        host = default_host
        port = default_port
        return (host, port)

    def run(self):
        """ Run the Gracie application """
        self.server.serve_forever()


def __main__(argv=None):
    """ Mainline code for this program """

    from sys import argv as sys_argv
    if argv is None:
        argv = sys_argv

    app = Gracie(argv)
    exitcode = None
    try:
        app.run()
    except SystemExit, e:
        exitcode = e.code

    return exitcode

if __name__ == "__main__":
    import sys
    exitcode = __main__(argv=sys.argv)
    sys.exit(exitcode)
