#! /usr/bin/make -f

# Makefile
# Part of Gracie, an OpenID provider
#
# Copyright © 2007 Ben Finney <ben+python@benfinney.id.au>
# This is free software; you may copy, modify and/or distribute this work
# under the terms of the GNU General Public License, version 2 or later.
# No warranty expressed or implied. See the file LICENSE for details.

# Makefile for gracie module

RM = rm

PYTHON = python


.PHONY: all
all:

.PHONY: test
test:
	@ $(PYTHON) ./test/suite.py

.PHONY: clean
clean:
