#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'gracie.devel',
 'build_date': '2008-09-12 15:23:21 +1000',
 'clean': None,
 'date': '2008-09-12 14:49:33 +1000',
 'revision_id': 'ben@benfinney.id.au-20080912044933-n5cv07i9eftf9gkb',
 'revno': 111}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
